name: Build and Publish Electron App

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.0'

      - name: Install dependencies
        run: npm install

      - name: Make the Electron app
        run: npm run make

      - name: Upload build artifacts (cross-platform sharing)
        uses: actions/upload-artifact@v3
        with:
          name: out-${{ matrix.os }}
          path: out/

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download macOS build artifact
        uses: actions/download-artifact@v3
        with:
          name: out-macos

      - name: Download Linux build artifact
        uses: actions/download-artifact@v3
        with:
          name: out-linux

      - name: Download Windows build artifact
        uses: actions/download-artifact@v3
        with:
          name: out-windows

      - name: Re-upload all artifacts for download
        uses: actions/upload-artifact@v3
        with:
          name: all-platforms-out
          path: out/
